src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 */
class Item
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_At;

    /**
     * @ORM\ManyToOne(targetEntity=Todolist::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $todolist_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeImmutable $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getTodolistId(): ?Todolist
    {
        return $this->todolist_id;
    }

    public function setTodolistId(?Todolist $todolist_id): self
    {
        $this->todolist_id = $todolist_id;

        return $this;
    }
}

src/Form/ItemType.php
<?php

namespace App\Form;

use App\Entity\Item;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('created_At')
            ->add('todolist_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Item::class,
        ]);
    }
}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Form\ItemType;
use App\Repository\ItemRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/item')]
class ItemController extends AbstractController
{
    #[Route('/', name: 'item_index', methods: ['GET'])]
    public function index(ItemRepository $itemRepository): Response
    {
        return $this->render('item/index.html.twig', [
            'items' => $itemRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'item_new', methods: ['GET', 'POST'])]
    public function CreateItem(Request $request, EntityManagerInterface $entityManager): Response
    {
        $item = new Item();
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('item_index', [], Response::HTTP_SEE_OTHER);
            sleep(1800);
        }

        return $this->renderForm('item/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }
}

templates/item/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item index{% endblock %}

{% block body %}
    <h1>Item index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Content</th>
                <th>Created_At</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.content }}</td>
                <td>{{ item.createdAt ? item.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('item_new') }}">Create new</a>
{% endblock %}

templates/item/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Item{% endblock %}

{% block body %}
    <h1>Create new Item</h1>

    {{ include('item/_form.html.twig') }}

    <a href="{{ path('item_index') }}">back to list</a>
{% endblock %}

templates/item/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item{% endblock %}

{% block body %}
    <h1>Item</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ item.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ item.content }}</td>
            </tr>
            <tr>
                <th>Created_At</th>
                <td>{{ item.createdAt ? item.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('item_index') }}">back to list</a>

    <a href="{{ path('item_edit', {'id': item.id}) }}">edit</a>

    {{ include('item/_delete_form.html.twig') }}
{% endblock %}